version: "3.2"
services:
  imepel-node:
    image: node:16.14.2
    container_name: test-brainag-front
    user: "root"
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    network_mode: "host"
    command: bash -c "npm install ; npm run start"
